Repository o-rumiantsev/Dirsync, pull requests merged in 2018-12, with the labels that each got.

#10 lib: method `send`
  lib/connection.js
  package-lock.json
  package.json
  test/connection.js
Labels: functionality, test

#13 fix: emit by order
  lib/connection.js
  test/connection.js
Labels: functionality, test

#12 fix: watcher emit data
  lib/fs-interface.js
  lib/log.js
  lib/watcher/create-watcher.js
  lib/watcher/index.js
  test/watcher.js
Labels: functionality, test

#18 fix: add some fixes to Connection class
  lib/connection.js
Labels: bug, fix

#17 feat: implement Server
  lib/fs-interface.js
  lib/server.js
  lib/watcher/index.js
  test/server.js
Labels: functionality, test

#19 feat: implement Client
  lib/client.js
  test/client.js
  test/fixtures/README.md
Labels: functionality, test

#24 refactor: watcher
  lib/log.js
  lib/watcher/create-watcher.js
  lib/watcher/index.js
  lib/watcher/lifetime-watcher.js
  lib/watcher/state-watcher.js
  lib/watcher/utils.js
  test/fixtures/README.md
  test/fixtures/watcher/README.md
  test/watcher.js
Labels: enhancement, test

#26 feat: add `readFileSubsystem` and `buildFileSubsystem`
  lib/fs-interface.js
Labels: functionality

#27 refactor, feat: embed new Watcher interface, add fetching data from synced dir
  lib/client.js
  lib/fs-interface.js
  lib/server.js
  lib/watcher/index.js
  test/client.js
  test/fixtures/sync/README.md
  test/server.js
  test/watcher.js
Labels: fix, functionality

#28 refactor, feat: add `postprocess` tree after JSON.parse
  lib/fs-interface.js
Labels: bug, enhancement, fix

#29 feat: implement entry point for a project
  index.js
Labels: enhancement

#33 fix: change client sync contract
  test/client.js
Labels: fix

#32 fix: add fileSubsystem tree postprocess
  lib/client.js
Labels: bug, fix

#34 fix: general
  index.js
  lib/client.js
  lib/connection.js
  lib/fs-interface.js
  test/fixtures/sync/README.md
  test/watcher.js
Labels: bug, fix

#36 feat: add CLI implementation
  bin/cli.js
  cli.sh
  lib/fs-interface.js
  lib/server.js
Labels: enhancement, functionality

#37 feat: add server address
  bin/cli.js
  lib/server.js
Labels: enhancement, functionality

#38 feat: add property `address` for connection
  bin/cli.js
  lib/connection.js
Labels: enhancement, functionality

#45 fix: consider ignored files in `readFileSubsystem`
  bin/cli.js
  lib/fs-interface.js
  lib/server.js
Labels: fix
